import turtle

turtle.Screen().bgcolor("black")
turtle.color("red")

turtle.penup()
turtle.home()
turtle.goto(-100, 0)
turtle.setheading(0)
turtle.pendown()
turtle.forward(200)
turtle.rt(144)
turtle.forward(200)
turtle.rt(144)
turtle.forward(200)
turtle.rt(144)
turtle.forward(200)
turtle.rt(144)
turtle.forward(200)
turtle.hideturtle()
turtle.done()